NUM_GPUS: 1
NUM_NODES: 1
RANK_ID: 0
DIST_BACKEND: "nccl"
RNG_SEED: 1
OUTPUT_DIR: 'outputs/cifar/mbv2_cifar100_224_e100_sgd'
TRAIN:
  LOG_STEP: 10
  GRADIENT_ACCUMULATE_STEP: 1
  MAX_EPOCH: 100
  SAVE_EPOCH: 1
  EVAL_EPOCH: 1
  RESUME: False
  USE_TENSORBOARD: True
  HYBRID_PRECISION: True
DCL:
  USE_DCL: False
  SWAP_SIZE: (7, 7)
  LAMBDA: 1.0
  BETA: 1.0
  GAMMA: 1.0
  TRAIN_METHODS: ('Normalize', 'ToTensor')
  TEST_METHODS: ('Normalize', 'ToTensor')
  NORMALIZE: ((0.445, 0.445, 0.445), (0.225, 0.225, 0.225), 255.0, 1.0)
  TO_TENSOR: 1.0
DATASET:
  NAME: 'CIFAR100'
  TRAIN_ROOT: './data/cifar'
  TEST_ROOT: './data/cifar'
  TOP_K: (1, 5)
TRANSFORM:
  TRAIN_METHODS: ('Rotate', 'HorizontalFlip', 'ColorJitter', 'SquarePad', 'Resize', 'RandomCrop', 'Normalize', 'ToTensor')
  TEST_METHODS: ('SquarePad', 'Resize', 'Normalize', 'ToTensor')
  ROTATE: ((-30, 30), 1, 4, None, 0.5)
  HORIZONTAL_FLIP: 0.5
  COLOR_JITTER: (0.2, 0.2, 0.2, 0.2, 0.5)
  SQUARE_PAD: ("center", 0, 0, 1.0)
  TRAIN_RESIZE: ((256, 256), 1, 1.0)
  TEST_RESIZE: ((224, 224), 1, 1.0)
  RANDOM_CROP: ((224, 224), 1.0)
  TEST_CENTER_CROP: ((224, 224), 1.0)
  NORMALIZE: ((0.485, 0.456, 0.406), (0.229, 0.224, 0.225), 255.0, 1.0)
  TO_TENSOR: 1.0
DATALOADER:
  TRAIN_BATCH_SIZE: 128
  TEST_BATCH_SIZE: 128
  NUM_WORKERS: 4
  RANDOM_SAMPLE: True
  PREFETCHER: True
MODEL:
  HEAD:
    NUM_CLASSES: 100
  RECOGNIZER:
    NAME: 'mobilenet_v2'
    PRELOADED: ""
    PRETRAINED: ""
  CRITERION:
    NAME: 'CrossEntropyLoss'
OPTIMIZER:
  NAME: 'SGD'
  LR: 0.05
  MOMENTUM: 0.9
  WEIGHT_DECAY:
    DECAY: 4e-5
    NO_BIAS: True
    NO_NORM: True
LR_SCHEDULER:
  NAME: 'MultiStepLR'
  IS_WARMUP: True
  GAMMA: 0.1
  MULTISTEP_LR:
    MILESTONES: [ 30, 55, 75, 90 ]
  WARMUP:
    ITERATION: 5
    MULTIPLIER: 1.0